.TH CONQUER 6
.SH NAME
conquer \- multiuser game of strategy
.SH SYNOPSIS
.B conquer
[-maxhps -nNAT -dDIR]
.SH DESCRIPTION
.I CONQUER
is a multi player computer game designed to run under the UNIX
operating system.  In
.I CONQUER
,  each player is the leader of a nation,
composed of people (humans, orcs, elves, dwarves), recourses, and land.
Rulers customize their nation at creation by chosing their race and by giving
their nation special powers (magic, combat factor, location, speed...)
and resources (civilians, troops, iron, gold...).  Play involves building,
moving, and controlling armies and navies, diplomacy with other players,
and adjusting economic activity, which is primarily geared to the production
of gold for your treasury.  Iron is needed, however to build ships & armies,
and food is needed to prevent revolts and keep people alive.
.SH ON LINE HELP
For detailed information, run conquer with the -h option (see below).
.SH OPTIONS
Command line format: conquer [-maxhps -nNAT -dDIR]
It is suggested that each player set up an alias for their game & nation.
My alias, for example, is
.I conquer -d/d7/c7913/smile/oldgame/lib -norcland
